In [2]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(r'C:\Users\user\my_snippet\synthetic_dataset.csv',encoding='UTF-8')
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

In [19]:
df.isnull().sum()
#percentage
df.isnull().mean()*100

Category    62.998624
Price        3.988996
Rating      46.996790
Stock       30.994956
Discount     8.986703
dtype: float64

In [21]:
df.duplicated().sum()

np.int64(15)

In [23]:
df['Category'] = df['Category'].fillna('X')
df['Rating'] = df['Rating'].fillna(df['Rating'].median())

In [42]:
# df['Price'].plot(kind='hist',bins=30)
# #df['Stock'].value_counts().plot(kind='hist',bins=30)
# df['Discount'].plot(kind='hist',bins=20)

In [41]:
# df.plot(kind='scatter',x='Price',y='Rating')
# df.plot(kind='scatter',x='Discount',y='Rating')

In [ ]:
df['Category'].fillna('X')
g = df.groupby('Category')
g['Price'].sum()
g['Rating'].agg(['max','mean','min'])

               max      mean       min
Category
A         4.992002  3.089706  1.016958
B         4.985116  3.098575  1.013644
C         4.992309  2.878008  1.000366
D         4.989577  3.116892  1.003437

In [ ]:
df.groupby('Stock')['Rating'].mean()
#widest price range
df.groupby('Category')['Price'].

In [16]:
df.loc[:5,:]

  Category   Price    Rating         Stock  Discount   price
0      NaN  5548.0  1.870322           NaN       0.0  5548.0
1      NaN  3045.0  4.757798           NaN      38.0  3045.0
2      NaN  4004.0       NaN      In Stock       0.0  4004.0
3      NaN  4808.0  1.492085           NaN      33.0  4808.0
4      NaN  1817.0       NaN  Out of Stock      23.0  1817.0
5      NaN  3522.0       NaN           NaN       NaN  3522.0

In [26]:
g = df.groupby('FilledCategory')['Price'].sum()

In [28]:
df['Category'] = df['Category'].fillna('Unknown')
df.head()

  Category   Price    Rating         Stock  Discount   price FilledCategory
0  Unknown  5548.0  1.870322           NaN       0.0  5548.0              X
1  Unknown  3045.0  4.757798           NaN      38.0  3045.0              X
2  Unknown  4004.0       NaN      In Stock       0.0  4004.0              X
3  Unknown  4808.0  1.492085           NaN      33.0  4808.0              X
4  Unknown  1817.0       NaN  Out of Stock      23.0  1817.0              X

In [39]:
# df['Price'].plot(kind='hist', bins=30)
# df['Stock'].value_counts().plot(kind='bar')

In [38]:
# df.plot(kind='scatter', x='Price', y='Rating')
# df.plot(kind='scatter', x='Discount', y='Rating')

In [40]:
#df['Rating'].plot(kind='kde')